### ISSUE TITLE
Complex template must reflect the recent changes

### ISSUE THREAD

**Issue by dmartinol** [parodos-dev/workflow-software-templates#27] opened 2024-03-11 12:26 UTC
Once completed, changes introduced in the Basic workflow template must be applied to the Complex workflow template for consistency.

**Comment by masayag** [comment] 2024-03-18 16:54
Duplicate of https://github.com/parodos-dev/workflow-software-templates/issues/17

**Closed by masayag** 2024-03-18 16:54 UTC
Labels: enhancement
